python source/train_embedding.py \
    --output_dir embeddings \
    --model_name_or_path bert-base-cased \
    --dataset acos_drone_binary \
    --label_name ac-sp \
    --strategy single \
    --stage 1 \
    --margin 0.5 \
    --num_epochs 3 \
    --batch_size 64 \
    --exclude_duplicate_negative